### ISSUE TITLE
monitored_conditions does not work

### ISSUE THREAD

**Issue by hajo62** [custom-components/sensor.avanza_stock#115]
I'm not sure if it's a bug or if I missunderstood the monitored_conditions option:

As a start and to test I have added:
```
  - platform: avanza_stock
    stock:
      - id: 4175
        name: IBM 
        shares: 1
        conversion_currency: 18987
        invert_conversion_currency: true
        purchase_date: 2008
        purchase_price: 75
        currency: €
    monitored_conditions:
      - change
      - changePercent
      - currency
      - name
```

I had expected to see just those 4 attributes but I see lots more:
<img width="344" alt="grafik" src="https://user-images.githubusercontent.com/15800980/116197649-49e85400-a735-11eb-8bae-1f0badd7019b.png">
