### ISSUE TITLE
Sensor not updating

### ISSUE THREAD

**Issue by Georgeleeh** [custom-components/sensor.avanza_stock#125]
Sorry if this is just a me problem but my stock sensors only seem to be updating when I reboot and I can't see a way to set the update frequency?

I've been rebooting a fair bit as I've been figuring out my config and every time I do, I get the latest price. But when the system is left it doesn't seem to be updating at all? At least, not anywhere near as frequently as I'd like. Is there a way to set the update frequency?

Here's my config:

```
sensor:
  - platform: avanza_stock
    stock:
      - id: 194698
        name: GME GBP 1
        shares: XX
        purchase_price: XXX
        conversion_currency: 455493
        invert_conversion_currency: true
      - id: 450548
        name: AMC GBP
        shares: XX
        purchase_price: XXX
        conversion_currency: 455493
        invert_conversion_currency: true
      - id: 194698
        name: GME GBP 2
        shares: XX
        purchase_price: XXX
        conversion_currency: 455493
        invert_conversion_currency: true
    monitored_conditions:
      - lastPrice
      - lastPriceUpdated
      - change
      - changePercent
      - name
```

Thanks!

**Comment by claha** [comment]
Default update interval is 1h, you can easily change it to 60s or whatever you prefer.
```yaml
- platform: avanza_stock
  scan_interval: 60
  stock:
```

Let me know if that helps :)
