### ISSUE TITLE
Speify to scan only during trading days and hours?

### ISSUE THREAD

**Issue by qerim** [custom-components/sensor.avanza_stock#126]
I have the following config:

```
- platform: avanza_stock
  scan_interval: 60
  stock:
    - id: 365296
      name: avanza_stock_vusa
      conversion_currency: 155735
    - id: 29747
      name: avanza_stock_v
```
However, as you can see, it's scanning every 60 minutes even after trading hours, which produces these flat line graphs:

![image](https://user-images.githubusercontent.com/3625009/141661929-fa57d209-2547-4d47-b351-917931b8f653.png)

Any way to get this to stop scanning after trading halts?
