### ISSUE TITLE
accept templates as element for the field "shares"

### ISSUE THREAD

**Issue by ggonmar** [custom-components/sensor.avanza_stock#185]
Proposing a nice enhancement:
I think it would be great if we could set the number of shares via a template, coming from an input number, or any other service:

```
- platform: avanza_stock
  stock:
    - id: 506278
      name: Stocks:Alibaba
      shares: {{ states("input_number.shares_of_alibaba") }}
      purchase_price: {{ states("input_number.purchase_price_alibaba") }} 
```

This way, one could easily update the sensor without having to dig into the code to change that value!
