### ISSUE TITLE
How do I use id 0?

### ISSUE THREAD

**Issue by mrjcohen** [custom-components/sensor.avanza_stock#188]
I have about 15 stocks but 3 of them were not available on Avanza so I used id=0 for them. Is there any way to update the stock price using a different entity? I was able to add the stock price to a Yahoo Finance Integration entity but that integration doesn't track number of shares and purchase price so it doesn't do all the cool calculations like you integration does.

**Comment by claha** [comment]
You use it like this

```yaml
    - id: 0
      name: off market stock
      shares: 100
      purchase_price: 100
      currency: SEK
```
So the purchase price is also the current price. Currently that is expectee to be just a number but it is definetly doable to have it reference another entity. I just update the purchase price every year when there is a new evaluation, this was my usecase for implementing the feature. 

What stock is it that you cant find on avanza?

**Comment by mrjcohen** [comment]
Hi, thanks for messaging back! The three stocks I can't find are [EQL](https://finance.yahoo.com/quote/EQL/), [DHS](https://finance.yahoo.com/quote/DHS/), & [BRCHF](https://finance.yahoo.com/quote/BRCHF/).

I was able to add entities for those stocks using the [Yahoo Finance HACS Integration](https://github.com/iprak/yahoofinance) so I was hoping there was a way to override the stock price with that entity.


For example if the stock price entity for EQL from the Yahoo Finance Integration is **sensor.yahoofinance_eql** then 

```yaml
    - id: 0
      name: EQL
      shares: 100
      purchase_price: 100
      stock_price: sensor.yahoofinance_eql
```

I'm not a developer so I'm not sure if that's possible
