### ISSUE TITLE
Allow to define multiple stocks

### ISSUE THREAD

**Issue by claha** [custom-components/sensor.avanza_stock#61]
Most people probably use the same manitored_conditions for all their sensors, it gets tidious to define the same for each sensor. Allow this kind of yaml configuration.
```yaml
sensor:
  - platform: avanza_stock
    stock:
      - id: 1234
        name: A
        shares: 10
      - id: 5678
        name: B
        shares: 20
    name: IGNORED!
    monitored_conditions:
      - change
```

The "global" name attribute will be ignored. Not sure if it is possible to have both this behaviour and the old one. If not this will be a breaking change.
